language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: lQBtD9SXj2hsEzW2/cx0aylkzdbx1AhZb30Lpb1WCgOxGqMtecJz6WO5vswHLzjTi/jS66T0tGK8ARax/dpA6DZEhn4xc388hNe0rUt305YLw04w2n1lYjdILeesGGGUOssqmyckmnEiVf3z3OcNaO6QhYffiwW52VDGAkppcNphHPNpIbfnEJD9S+pHb8AE1tp0+8vfQ8y2rDJ2At2fOTHd2CkrUnfe0NKG6c0vxEw1aFFMzEekdua6hlaWG0AzAWx25GbfLIBJVbei5l4EYcIvh70UZyITHAwdqHTCNsTOqiglmcaeNVeyu19UXFvGPeBoPmIfEThUBoD8MDx6ifAGb5daQ1LhKhbG9njfLxQh3mXe6XJodSNcReHr6ySRLBjJ1f0Pvkg9f56zO51xp4NksZ2Kl42R+mF+oM79X2Kzr4tWhg3I8CGPl3f7PIqxISZwKFiTen2b8E8fhBg7Q8Z9j3Km+qyMImw2zI4EWdCJ3x6MFz+onOj6W1KG7ejf2LO9Ilx7eFOql6wNGCb/W8RPq8ITGA5Oe6KtNAok439S0gDi8/Qg1kbriHlD0esfmGxw1JxqfD2Btlz+PYHZ4z5WaW1X9GkNW627zW0tzV92IK8EISczz52kpE9FqAgh6qwwTarPHWxI4lqk6FpjrvGm3UOhG1KiBER8KsoeFmE=
  app: random-word-110
