language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: fmxTHbT/auSNudXFduUeAEFtLl43HQD45ihnw6e+S5pD9YjwsxhUmHkQUTMf6Quj5qLUYiPVaJebwbrp3jN9TKC8KpkR8Xy3UbNu2BOFnzwKyPISHjbBq5kleQws88ol3nEiZe3jK/Bac6Qk/HHf9dJ/q+eznyg9uDfCvT8xAIImHb2Z7Gh4+pAG+snyur3EbqXSOSvoFD5cVSCSJPxxfwyjA/QH9kt4625x+/+2qhb9g0f93FU261RjrU/phAP+ClNsv00t7aUi4heP9TQfwQxasQngzQZeQhW0qJhSIt3TAC9Ul9ZbiMXNL3ZAgYBXUnJSKZ9r9zCVMX9lIsilBPxrx9Rj0s4+JSaFAPW8NHrcpX6+Z8IHyZLyvBRRX+8phNyc7QPPX+mikuz/jHANi823Jh2DVscse0pwhzU9O6ptZY+GNbDxQ4L7do7W6c8j5jjIOfUdUEP8/+7NJlZu9BujyJLN+aFt3AkoEgMCxy9eTTskwB2fgK0LdQiZfRzn5tSuwsFVI5DW3dDvl0K7GUO9JNtbDNsDekIACC4w8rZzzIs5aWiJbcDeFo3UILgbBgWEt8NnZOkjsE74QiUHFWpCLGdPPUWlTNTCFud/BwmCtp0hy5tlWq8aQWruvMk0EgkqRse+pNMOQ4lfg7eLGt2GeCrfDm7B60r/Im/BDH4=
  app: random-word-110
