language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: "kEE8Bkw1n+2ZHpSdox/3XyL3mCZmZHgOy8HTKb1RZSC0lUCTYeD9bKWLpL6ZmePxV2lQ1QDhpNDMV9Bt6vTApUqwC8kMjY4W9egVa0FNh8ntco7KC9lbmvZsZ7ISDPyhUNx3KgWDGNl+MX2z70NAMMK8vCWX1wBjVyVex7l2lexUpRY0NDle2JFrHqC+o30BnRz9IHWJdqM1L9v3Pp+EF2kHKkMGj4RFtUOdAy3XWnjlMzD22mfAWHAc8jQOc4AfVLZH/al1RvtQvQHltezTm+00BQ88+QdQro3Odoz1OzR+C3LX4cPlGjUNde0ee7ZLsW7T4oy8rcfcmuxQ2xYZrdCeqtQZsDUTWZzi2YxGWjjyCsTCFTow/6s6HoUVjlN54vV4Q8GIbjewgCUFfccz97lzdEmvR9gG2f+K1V5XY3dYQQOFh8WZnQ4iKW4fdEpWjio0u1MSrkeK0CuF8WK63649rU4ZYj0fmeM2AkEIBQ1AUsM+5DPJO+YatTGwGyknuX2VDXOB9vk/+1hHkIrCoLe3IPiWkwhCL/R5LM6+fig/qejnKQglZOrZXYpFmhrDyhTvHnJuV4ZuRuS2GdJH8iqZIfi3gVW4ngvde03c+YRNaHK/cWWnWqJWsblP1lIUb8BKGRMBnF61z2xEH5EvPUd1wQwDIBgG3Dd9HGTcWDM="
  app: random-word-110